version: '3'

services:
  sma-stats:
    image: sma-stats:latest
    container_name: sma-stats
    ports:
      - 8080:80
    environment:
      - smadb_ip=192.168.1.3
      - smadb_port=8086
      - smadb_db=SMA
      - smadb_user=user
      - smadb_pw=pw
      - emdb_ip=192.168.1.3
      - emdb_port=8086
      - emdb_db=measurements
      - emdb_user=user
      - emdb_pw=pw
      - lang=en
      - table_borders=yes
      - chart=all
      - max_solar=no
      - baseline=no
      - time_solar=0
      - days=0
      - nounits=no
      - onlychart=no
      - onlytable=no
      - wmdb_ip=192.168.1.3
      - wmdb_port=8086
      - wmdb_db=measurements
      - wmdb_user=user
      - wmdb_pw=pw
      - wmlang=en
      - wmtable_borders=yes
      - wmchart=all
      - wmonlychart=no
      - wmdays=14
    restart: unless-stopped
